<?xml version="1.0"?>
<package format="2">
  <name>control</name>
  <version>0.1.0</version>
  <description>Pure Pursuit and Stanley path tracking for the HENES T870.</description>

  <maintainer email="stier@todo.todo">STIER</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>erp42_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>planning_interfaces</depend>
  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>

  <test_depend>gtest</test_depend>

  <export/>
</package>
