<?xml version="1.0"?>
<package format="2">
  <name>sensor_bringup</name>
  <version>0.1.0</version>
  <description>Combined sensor and optional Arduino bringup for Team Stier.</description>

  <maintainer email="stier@todo.todo">stier</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>cam_bringup</exec_depend>
  <exec_depend>gps_bringup</exec_depend>
  <exec_depend>imu_bringup</exec_depend>
  <exec_depend>lidar_bringup</exec_depend>
  <exec_depend>roslaunch</exec_depend>
  <exec_depend>vehicle_interface_bringup</exec_depend>

  <test_depend>python3-nose</test_depend>
</package>
